;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append-line
        evil-backward-char
        evil-delete-backward-char-and-join
        evil-force-normal-state
        evil-forward-char
        evil-insert
        evil-next-line
        evil-normal-state
        evil-previous-line
        evil-record-macro
        evil-undo
        evil-append
        evil-insert-line
        ))
